### ISSUE TITLE
Component is missing template or render function

### ISSUE THREAD

**Issue by yexiaodong** [qiuquanwu/vue3-json-viewer#1]
runtime-dom.esm-bundler-bda63781.js:1184 [Vue warn]: Component is missing template or render function. 
  at <Anonymous value= {name: "qiu", age: 18, isMan: false, date: Tue Mar 09 2021 16:02:54 GMT+0800 (GMT+08:00), fn: ƒ, …} copyable="" boxed=""  ... > 
  at <PluginJson onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > class="page" > 
  at <KeepAlive include= [] > 
  at <RouterView> 
  at <App>

**Comment by yexiaodong** [comment]
就是vue3，用vite1搭建的

**Comment by qiuquanwu** [comment]
可以看看你的代码吗？就是使用这个组件的部分

**Comment by yexiaodong** [comment]
https://gitee.com/yexiaodong/do-vue

**Comment by qiuquanwu** [comment]
没看到在哪里引用了啊

**Comment by yexiaodong** [comment]
src/module/alpha/views/PluginJson.vue

**Comment by yexiaodong** [comment]
`
<template>
<div class="alphaPluginJson">
    <l-header title="json"></l-header>
    <json-viewer :value="jsonData" copyable boxed sort />
</div>
</template>

<script>
import LHeader from '/@/common/components/layout/LHeader.vue'
import JsonViewer from "vue3-json-viewer"
export default {
    name: 'alphaPluginJson',
    components: { LHeader,JsonViewer },
    data() {
        return {
            jsonData: {
                name: "qiu", //字符串
                age: 18, //数组
                isMan: false, //布尔值
                date: new Date(),
                fn: () => {},
                arr: [1, 2, 5]
            }
        }
    },
    methods: {
        getData() {
            //方法
        }
    },
    mounted() {}
};
</script>

<style lang="scss" scoped>
.alphaPluginJson {
    margin-top: 46px;
}
</style>

`

**Comment by yexiaodong** [comment]
`<template>
<div class="alphaPluginJson">
    <l-header title="json"></l-header>
    <json-viewer :value="jsonData" copyable boxed sort />
</div>
</template>

<script>
import LHeader from '/@/common/components/layout/LHeader.vue'
import JsonViewer from "vue3-json-viewer"
export default {
    name: 'alphaPluginJson',
    components: { LHeader,JsonViewer },
    data() {
        return {
            jsonData: {
                name: "qiu", //字符串
                age: 18, //数组
                isMan: false, //布尔值
                date: new Date(),
                fn: () => {},
                arr: [1, 2, 5]
            }
        }
    },
    methods: {
        getData() {
            //方法
        }
    },
    mounted() {}
};
</script>

<style lang="scss" scoped>
.alphaPluginJson {
    margin-top: 46px;
}
</style>
`

**Comment by yexiaodong** [comment]
![image](https://user-images.githubusercontent.com/13914749/110440178-59fb9400-80f3-11eb-897a-8d0d75249826.png)

**Comment by qiuquanwu** [comment]
看到了，你可以用vue3的写法试试

**Comment by qiuquanwu** [comment]
你在mian.js使用app.use注册组件试试，

**Comment by yexiaodong** [comment]
刚刚试了你的方法，一样有这个错误（PS：我使用局部导入组件，非全局导入）

**Comment by qiuquanwu** [comment]
这个我倒是没试过，我有时间试试，看看什么问题

**Comment by yexiaodong** [comment]
可以了，你的组件必须在main.js中全局导入

**Comment by yexiaodong** [comment]
可以优化一下吗，因为这个组件不常用，不想全局导入

**Comment by qiuquanwu** [comment]
vue3有些不一样，你可以在组件内引用，但是你标签名得用<JsonViewer></JsonViewer>,你用vue3，还是得用vue3的写法，使用compositionAPI+script-setup

**Comment by qiuquanwu** [comment]
vue3有些不一样，你可以在组件内引用，但是你标签名得用<JsonViewer>，你用vue3最好还是用vue3的写法，使用compositionAPI+script-setup

**Comment by qiuquanwu** [comment]
close
