### ISSUE TITLE
tsx 使用时有问题

### ISSUE THREAD

**Issue by g0ngjie** [qiuquanwu/vue3-json-viewer#11]
vite@2.9.9 vue@3.2.25 tsx方式 也添加了vue3-json-viewer.d.ts，但还是运行不起来，终端报错
错误信息如下：
[vite] Internal server error: unknown: Property left of AssignmentExpression expected node to be of a type ["LVal"] but instead got "StringLiteral"

**Comment by qiuquanwu** [comment]
这个不是vue3-json-viewer的问题哦，我自己测试是没有这个问题的
