### ISSUE TITLE
不能动态添加数据

### ISSUE THREAD

**Issue by w582745483** [qiuquanwu/vue3-json-viewer#12]
<el-button type="" @click="testData">test</el-button>

  <json-viewer theme="my-awesome-json-theme" :value="test" :expand-depth="3" copyable boxed sort> </json-viewer>

const test = ref([{ name: 'xxx' }]);
const testData = () => {
  test.value.push({ name: '111' });
};
上面代码完全不能生效，json-viewer没有更新数据

**Comment by qiuquanwu** [comment]
```js
test.value=[...test.value,{ name: '111' }]
```
试试
