### ISSUE TITLE
为什么局部引用没用了

### ISSUE THREAD

**Issue by dute7liang** [qiuquanwu/vue3-json-viewer#13]
![image](https://user-images.githubusercontent.com/31098086/197511375-57c83108-efe9-4305-bcb8-2ec0afa98edf.png)
完全按你的写法来的，
但是我用全局引用就可以

**Comment by dute7liang** [comment]
vue3+ts 环境

**Comment by qiuquanwu** [comment]
有报错提示吗

**Comment by Hiram-Wong** [comment]
存在一样的问题，没有报错信息，dom 节点也不存在
