### ISSUE TITLE
vue3+webpack 好像就不太行了

### ISSUE THREAD

**Issue by oujin-nb** [qiuquanwu/vue3-json-viewer#2]

**Comment by oujin-nb** [comment]
是我自己的原因 我用的ts ，忽视一下引入包类型就行了。,,ԾㅂԾ,,

**Comment by qiuquanwu** [comment]
@ou-jin  可以看一下[ typescript支持](https://vjv-doc-qiuquanwu.vercel.app/#typescript%E6%94%AF%E6%8C%81)
