### ISSUE TITLE
vue3.1 版本无法渲染

### ISSUE THREAD

**Issue by zhuqingguang** [qiuquanwu/vue3-json-viewer#3]
![image](https://user-images.githubusercontent.com/24694223/134839361-a44b0648-3b97-4991-bb6e-9eddaf2b2e9a.png)
能帮忙看下是什么原因吗

**Comment by zhuqingguang** [comment]
全局注册时会出现这个问题，单独引入是没问题的

**Comment by qiuquanwu** [comment]
那你用3.2版本吧

**Comment by qiuquanwu** [comment]
resolve

**Comment by qiuquanwu** [comment]
c
