### ISSUE TITLE
import "./index.css" is in the esm bundle

### ISSUE THREAD

**Issue by Darkle** [qiuquanwu/vue3-json-viewer#5]
Hi, there seems to be an `import "./index.css"` in the esm bundle: https://unpkg.com/vue3-json-viewer@1.0.4/dist/bundle.esm.js

**Comment by qiuquanwu** [comment]
if you used v1.0.5, you should add `import "vue3-json-viewer/dist/index.css";`

**Comment by qiuquanwu** [comment]
resolved
