### ISSUE TITLE
无法找到模块“vue3-json-viewer”的声明文件

### ISSUE THREAD

**Issue by yexiaodong** [qiuquanwu/vue3-json-viewer#7]
![image](https://user-images.githubusercontent.com/13914749/159216285-b9d04abb-6640-4f39-9cdd-5e9bf732700c.png)

**Comment by qiuquanwu** [comment]
https://vjv-doc-qiuquanwu.vercel.app/#typescript%E6%94%AF%E6%8C%81

**Comment by qiuquanwu** [comment]
close
